### ISSUE TITLE
Error: Received an invalid JSON format

### ISSUE THREAD

**Issue by cfjedimaster** [textlint-rule/textlint-rule-ginger#79]
Testing with an HTML file, and I get this:

```
✖ Error
Received an invalid JSON format
at /Users/rcamden/projects/textlinttest/targeted-offers.guide.v2.html

✖ Stack trace
Error: Received an invalid JSON format
    at Request._callback (/Users/rcamden/projects/textlinttest/node_modules/gingerbread/index.js:31:23)
    at Request.self.callback (/Users/rcamden/projects/textlinttest/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Users/rcamden/projects/textlinttest/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Users/rcamden/projects/textlinttest/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by melg8** [comment]
I've encountered same issue with regular .md file, using version 2.2.1. Sometimes it happens on check, and sometimes - not, without any changes.
Log example:
``` bash

✖ Stack trace
Error: Received an invalid JSON format
at /home/user/work/readme.md
    at Request._callback (/nix/store/mcc0fb7sdw48l09cxvj9psw53qwk0zqy-node-dependencies-text_lint_nix-1.0.0/lib/node_modules/gingerbread/index.js:31:23)
    at Request.self.callback (/nix/store/mcc0fb7sdw48l09cxvj9psw53qwk0zqy-node-dependencies-text_lint_nix-1.0.0/lib/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/nix/store/mcc0fb7sdw48l09cxvj9psw53qwk0zqy-node-dependencies-text_lint_nix-1.0.0/lib/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/nix/store/mcc0fb7sdw48l09cxvj9psw53qwk0zqy-node-dependencies-text_lint_nix-1.0.0/lib/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)


```
